program Project1;

uses
  Vcl.Forms,

  Curl.Lib in '..\thirds\curl4delphi\Src\Curl.Lib.pas',
  ZLibExApi in '..\thirds\DelphiZLib\ZLibExApi.pas',
  ZLibExGZ in '..\thirds\DelphiZLib\ZLibExGZ.pas',
  ZLibEx in '..\thirds\DelphiZLib\ZLibEx.pas',
  BR in '..\thirds\BR.pas',
  GZIP in '..\thirds\GZIP.pas',

  Constants.ContentType in '..\consts\Constants.ContentType.pas',
  Constants.GeminiEnumType in '..\consts\Constants.GeminiEnumType.pas',
  Constants.HttpStatusCode in '..\consts\Constants.HttpStatusCode.pas',
  Constants.ImagenEnumType in '..\consts\Constants.ImagenEnumType.pas',
  Constants.MimeType in '..\consts\Constants.MimeType.pas',
  Constants.ParameterName in '..\consts\Constants.ParameterName.pas',
  Constants.ProtocolType in '..\consts\Constants.ProtocolType.pas',
  Constants.RequestMethod in '..\consts\Constants.RequestMethod.pas',

  Functions.StringsUtils in '..\funcs\Functions.StringsUtils.pas',
  Functions.SystemExtended in '..\funcs\Functions.SystemExtended.pas',

  Parameters.BasedParameterImplement in '..\params\based\Parameters.BasedParameterImplement.pas',
  Parameters.BasedParameterStatement in '..\params\based\Parameters.BasedParameterStatement.pas',

  Parameters.HttpworkImplement in '..\params\network\Parameters.HttpworkImplement.pas',
  Parameters.HttpworkStatement in '..\params\network\Parameters.HttpworkStatement.pas',
  Parameters.NetworkImplement in '..\params\network\Parameters.NetworkImplement.pas',
  Parameters.NetworkStatement in '..\params\network\Parameters.NetworkStatement.pas',

  Parameters.AttributionSourceId in '..\params\gemini\internal\Parameters.AttributionSourceId.pas',
  Parameters.BatchStats in '..\params\gemini\internal\Parameters.BatchStats.pas',
  Parameters.Blob in '..\params\gemini\internal\Parameters.Blob.pas',
  Parameters.CachedContent in '..\params\gemini\internal\Parameters.CachedContent.pas',
  Parameters.Candidate in '..\params\gemini\internal\Parameters.Candidate.pas',
  Parameters.Chunk in '..\params\gemini\internal\Parameters.Chunk.pas',
  Parameters.ChunkData in '..\params\gemini\internal\Parameters.ChunkData.pas',
  Parameters.ChunkingConfig in '..\params\gemini\internal\Parameters.ChunkingConfig.pas',
  Parameters.CitationMetadata in '..\params\gemini\internal\Parameters.CitationMetadata.pas',
  Parameters.CitationSource in '..\params\gemini\internal\Parameters.CitationSource.pas',
  Parameters.CodeExecution in '..\params\gemini\internal\Parameters.CodeExecution.pas',
  Parameters.CodeExecutionResult in '..\params\gemini\internal\Parameters.CodeExecutionResult.pas',
  Parameters.ComputerUse in '..\params\gemini\internal\Parameters.ComputerUse.pas',
  Parameters.Condition in '..\params\gemini\internal\Parameters.Condition.pas',
  Parameters.Content in '..\params\gemini\internal\Parameters.Content.pas',
  Parameters.ContentEmbedding in '..\params\gemini\internal\Parameters.ContentEmbedding.pas',
  Parameters.CustomMetadata in '..\params\gemini\internal\Parameters.CustomMetadata.pas',
  Parameters.Document in '..\params\gemini\internal\Parameters.Document.pas',
  Parameters.DynamicRetrievalConfig in '..\params\gemini\internal\Parameters.DynamicRetrievalConfig.pas',
  Parameters.EmbedContentBatch in '..\params\gemini\internal\Parameters.EmbedContentBatch.pas',
  Parameters.EmbedContentBatchOutput in '..\params\gemini\internal\Parameters.EmbedContentBatchOutput.pas',
  Parameters.EmbedContentBatchStats in '..\params\gemini\internal\Parameters.EmbedContentBatchStats.pas',
  Parameters.EmbedContentRequest in '..\params\gemini\internal\Parameters.EmbedContentRequest.pas',
  Parameters.EmbedContentResponse in '..\params\gemini\internal\Parameters.EmbedContentResponse.pas',
  Parameters.Example in '..\params\gemini\internal\Parameters.Example.pas',
  Parameters.ExecutableCode in '..\params\gemini\internal\Parameters.ExecutableCode.pas',
  Parameters.FileData in '..\params\gemini\internal\Parameters.FileData.pas',
  Parameters.FileInfo in '..\params\gemini\internal\Parameters.FileInfo.pas',
  Parameters.FileSearch in '..\params\gemini\internal\Parameters.FileSearch.pas',
  Parameters.FileSearchStore in '..\params\gemini\internal\Parameters.FileSearchStore.pas',
  Parameters.FunctionCall in '..\params\gemini\internal\Parameters.FunctionCall.pas',
  Parameters.FunctionCallingConfig in '..\params\gemini\internal\Parameters.FunctionCallingConfig.pas',
  Parameters.FunctionDeclaration in '..\params\gemini\internal\Parameters.FunctionDeclaration.pas',
  Parameters.FunctionResponse in '..\params\gemini\internal\Parameters.FunctionResponse.pas',
  Parameters.FunctionResponseBlob in '..\params\gemini\internal\Parameters.FunctionResponseBlob.pas',
  Parameters.FunctionResponsePart in '..\params\gemini\internal\Parameters.FunctionResponsePart.pas',
  Parameters.GenerateContentBatch in '..\params\gemini\internal\Parameters.GenerateContentBatch.pas',
  Parameters.GenerateContentBatchOutput in '..\params\gemini\internal\Parameters.GenerateContentBatchOutput.pas',
  Parameters.GenerateContentBatchRequest in '..\params\gemini\internal\Parameters.GenerateContentBatchRequest.pas',
  Parameters.GenerateContentRequest in '..\params\gemini\internal\Parameters.GenerateContentRequest.pas',
  Parameters.GenerateContentRequest2 in '..\params\gemini\internal\Parameters.GenerateContentRequest2.pas',
  Parameters.GenerateContentResponse in '..\params\gemini\internal\Parameters.GenerateContentResponse.pas',
  Parameters.GenerationConfig in '..\params\gemini\internal\Parameters.GenerationConfig.pas',
  Parameters.GoogleMaps in '..\params\gemini\internal\Parameters.GoogleMaps.pas',
  Parameters.GoogleSearch in '..\params\gemini\internal\Parameters.GoogleSearch.pas',
  Parameters.GoogleSearchRetrieval in '..\params\gemini\internal\Parameters.GoogleSearchRetrieval.pas',
  Parameters.GroundingAttribution in '..\params\gemini\internal\Parameters.GroundingAttribution.pas',
  Parameters.GroundingChunk in '..\params\gemini\internal\Parameters.GroundingChunk.pas',
  Parameters.GroundingMetadata in '..\params\gemini\internal\Parameters.GroundingMetadata.pas',
  Parameters.GroundingPassageId in '..\params\gemini\internal\Parameters.GroundingPassageId.pas',
  Parameters.GroundingSupport in '..\params\gemini\internal\Parameters.GroundingSupport.pas',
  Parameters.ImageConfig in '..\params\gemini\internal\Parameters.ImageConfig.pas',
  Parameters.InlinedEmbedContentRequest in '..\params\gemini\internal\Parameters.InlinedEmbedContentRequest.pas',
  Parameters.InlinedEmbedContentRequests in '..\params\gemini\internal\Parameters.InlinedEmbedContentRequests.pas',
  Parameters.InlinedEmbedContentResponse in '..\params\gemini\internal\Parameters.InlinedEmbedContentResponse.pas',
  Parameters.InlinedEmbedContentResponses in '..\params\gemini\internal\Parameters.InlinedEmbedContentResponses.pas',
  Parameters.InlinedRequest in '..\params\gemini\internal\Parameters.InlinedRequest.pas',
  Parameters.InlinedRequests in '..\params\gemini\internal\Parameters.InlinedRequests.pas',
  Parameters.InlinedResponse in '..\params\gemini\internal\Parameters.InlinedResponse.pas',
  Parameters.InlinedResponses in '..\params\gemini\internal\Parameters.InlinedResponses.pas',
  Parameters.InputConfig in '..\params\gemini\internal\Parameters.InputConfig.pas',
  Parameters.InputEmbedContentConfig in '..\params\gemini\internal\Parameters.InputEmbedContentConfig.pas',
  Parameters.Interval in '..\params\gemini\internal\Parameters.Interval.pas',
  Parameters.LatLng in '..\params\gemini\internal\Parameters.LatLng.pas',
  Parameters.LogprobsCandidate in '..\params\gemini\internal\Parameters.LogprobsCandidate.pas',
  Parameters.LogprobsResult in '..\params\gemini\internal\Parameters.LogprobsResult.pas',
  Parameters.Maps in '..\params\gemini\internal\Parameters.Maps.pas',
  Parameters.Message in '..\params\gemini\internal\Parameters.Message.pas',
  Parameters.MessagePrompt in '..\params\gemini\internal\Parameters.MessagePrompt.pas',
  Parameters.MetadataFilter in '..\params\gemini\internal\Parameters.MetadataFilter.pas',
  Parameters.ModalityTokenCount in '..\params\gemini\internal\Parameters.ModalityTokenCount.pas',
  Parameters.Model in '..\params\gemini\internal\Parameters.Model.pas',
  Parameters.MultiSpeakerVoiceConfig in '..\params\gemini\internal\Parameters.MultiSpeakerVoiceConfig.pas',
  Parameters.Operation in '..\params\gemini\internal\Parameters.Operation.pas',
  Parameters.Part in '..\params\gemini\internal\Parameters.Part.pas',
  Parameters.PlaceAnswerSources in '..\params\gemini\internal\Parameters.PlaceAnswerSources.pas',
  Parameters.PrebuiltVoiceConfig in '..\params\gemini\internal\Parameters.PrebuiltVoiceConfig.pas',
  Parameters.PromptFeedback in '..\params\gemini\internal\Parameters.PromptFeedback.pas',
  Parameters.RelevantChunk in '..\params\gemini\internal\Parameters.RelevantChunk.pas',
  Parameters.RetrievalConfig in '..\params\gemini\internal\Parameters.RetrievalConfig.pas',
  Parameters.RetrievalMetadata in '..\params\gemini\internal\Parameters.RetrievalMetadata.pas',
  Parameters.RetrievedContext in '..\params\gemini\internal\Parameters.RetrievedContext.pas',
  Parameters.ReviewSnippet in '..\params\gemini\internal\Parameters.ReviewSnippet.pas',
  Parameters.SafetyRating in '..\params\gemini\internal\Parameters.SafetyRating.pas',
  Parameters.SafetySetting in '..\params\gemini\internal\Parameters.SafetySetting.pas',
  Parameters.Schema in '..\params\gemini\internal\Parameters.Schema.pas',
  Parameters.SearchEntryPoint in '..\params\gemini\internal\Parameters.SearchEntryPoint.pas',
  Parameters.Segment in '..\params\gemini\internal\Parameters.Segment.pas',
  Parameters.SemanticRetrieverChunk in '..\params\gemini\internal\Parameters.SemanticRetrieverChunk.pas',
  Parameters.SpeakerVoiceConfig in '..\params\gemini\internal\Parameters.SpeakerVoiceConfig.pas',
  Parameters.SpeechConfig in '..\params\gemini\internal\Parameters.SpeechConfig.pas',
  Parameters.Status in '..\params\gemini\internal\Parameters.Status.pas',
  Parameters.StringList in '..\params\gemini\internal\Parameters.StringList.pas',
  Parameters.TextPrompt in '..\params\gemini\internal\Parameters.TextPrompt.pas',
  Parameters.ThinkingConfig in '..\params\gemini\internal\Parameters.ThinkingConfig.pas',
  Parameters.Tool in '..\params\gemini\internal\Parameters.Tool.pas',
  Parameters.ToolConfig in '..\params\gemini\internal\Parameters.ToolConfig.pas',
  Parameters.TopCandidates in '..\params\gemini\internal\Parameters.TopCandidates.pas',
  Parameters.UrlContext in '..\params\gemini\internal\Parameters.UrlContext.pas',
  Parameters.UrlContextMetadata in '..\params\gemini\internal\Parameters.UrlContextMetadata.pas',
  Parameters.UrlMetadata in '..\params\gemini\internal\Parameters.UrlMetadata.pas',
  Parameters.UsageMetadata in '..\params\gemini\internal\Parameters.UsageMetadata.pas',
  Parameters.UsageMetadataCaching in '..\params\gemini\internal\Parameters.UsageMetadataCaching.pas',
  Parameters.VideoFileMetadata in '..\params\gemini\internal\Parameters.VideoFileMetadata.pas',
  Parameters.VideoMetadata in '..\params\gemini\internal\Parameters.VideoMetadata.pas',
  Parameters.VoiceConfig in '..\params\gemini\internal\Parameters.VoiceConfig.pas',
  Parameters.Web in '..\params\gemini\internal\Parameters.Web.pas',
  Parameters.WhiteSpaceConfig in '..\params\gemini\internal\Parameters.WhiteSpaceConfig.pas',

  Parameters.AsyncBatchEmbedContentRequestBody in '..\params\gemini\Parameters.AsyncBatchEmbedContentRequestBody.pas',
  Parameters.BatchEmbedContentsRequestBody in '..\params\gemini\Parameters.BatchEmbedContentsRequestBody.pas',
  Parameters.BatchEmbedContentsResponseBody in '..\params\gemini\Parameters.BatchEmbedContentsResponseBody.pas',
  Parameters.BatchGenerateContentRequestBody in '..\params\gemini\Parameters.BatchGenerateContentRequestBody.pas',
  Parameters.CountMessageTokensRequestBody in '..\params\gemini\Parameters.CountMessageTokensRequestBody.pas',
  Parameters.CountMessageTokensResponseBody in '..\params\gemini\Parameters.CountMessageTokensResponseBody.pas',
  Parameters.CountTextTokensRequestBody in '..\params\gemini\Parameters.CountTextTokensRequestBody.pas',
  Parameters.CountTextTokensResponseBody in '..\params\gemini\Parameters.CountTextTokensResponseBody.pas',
  Parameters.CountTokensRequestBody in '..\params\gemini\Parameters.CountTokensRequestBody.pas',
  Parameters.CountTokensResponseBody in '..\params\gemini\Parameters.CountTokensResponseBody.pas',
  Parameters.EmbedContentRequestBody in '..\params\gemini\Parameters.EmbedContentRequestBody.pas',
  Parameters.EmbedContentResponseBody in '..\params\gemini\Parameters.EmbedContentResponseBody.pas',
  Parameters.GenerateContentRequestBody in '..\params\gemini\Parameters.GenerateContentRequestBody.pas',
  Parameters.GenerateContentResponseBody in '..\params\gemini\Parameters.GenerateContentResponseBody.pas',
  Parameters.ImportFileRequestBody in '..\params\gemini\Parameters.ImportFileRequestBody.pas',
  Parameters.ListCachedContentsResponseBody in '..\params\gemini\Parameters.ListCachedContentsResponseBody.pas',
  Parameters.ListFileResponseBody in '..\params\gemini\Parameters.ListFileResponseBody.pas',
  Parameters.ListFileSearchStoresDocumentResponseBody in '..\params\gemini\Parameters.ListFileSearchStoresDocumentResponseBody.pas',
  Parameters.ListFileSearchStoresResponseBody in '..\params\gemini\Parameters.ListFileSearchStoresResponseBody.pas',
  Parameters.ListModelResponseBody in '..\params\gemini\Parameters.ListModelResponseBody.pas',
  Parameters.ListOperationsResponseBody in '..\params\gemini\Parameters.ListOperationsResponseBody.pas',
  Parameters.PredictRequestBody in '..\params\gemini\Parameters.PredictRequestBody.pas',
  Parameters.PredictResponseBody in '..\params\gemini\Parameters.PredictResponseBody.pas',
  Parameters.QueryFileSearchStoresDocumentsRequestBody in '..\params\gemini\Parameters.QueryFileSearchStoresDocumentsRequestBody.pas',
  Parameters.QueryFileSearchStoresDocumentsResponseBody in '..\params\gemini\Parameters.QueryFileSearchStoresDocumentsResponseBody.pas',
  Parameters.UploadFilesRequestBody in '..\params\gemini\Parameters.UploadFilesRequestBody.pas',
  Parameters.UploadFilesResponseBody in '..\params\gemini\Parameters.UploadFilesResponseBody.pas',
  Parameters.UploadToFileSearchStoreRequestBody in '..\params\gemini\Parameters.UploadToFileSearchStoreRequestBody.pas',
  Parameters.UploadToFileSearchStoreResponseBody in '..\params\gemini\Parameters.UploadToFileSearchStoreResponseBody.pas',

  Tools.HttpworkImplement in '..\tools\Tools.HttpworkImplement.pas',
  Tools.HttpworkImplementWithCURL in '..\tools\Tools.HttpworkImplementWithCURL.pas',
  Tools.HttpworkStatement in '..\tools\Tools.HttpworkStatement.pas',
  Tools.NetworkImplement in '..\tools\Tools.NetworkImplement.pas',
  Tools.NetworkStatement in '..\tools\Tools.NetworkStatement.pas',

  Models.BasedModelImplement in '..\models\based\Models.BasedModelImplement.pas',
  Models.BasedModelStatement in '..\models\based\Models.BasedModelStatement.pas',

  Models.GeminiBasedModelImplement in '..\models\gemini\based\Models.GeminiBasedModelImplement.pas',
  Models.GeminiBasedModelStatement in '..\models\gemini\based\Models.GeminiBasedModelStatement.pas',

  Models.BatchesModelImplement in '..\models\gemini\Models.BatchesModelImplement.pas',
  Models.CachedContentsModelImplement in '..\models\gemini\Models.CachedContentsModelImplement.pas',
  Models.EmbeddingsModelImplement in '..\models\gemini\Models.EmbeddingsModelImplement.pas',
  Models.FileSearchStoresModelImplement in '..\models\gemini\Models.FileSearchStoresModelImplement.pas',
  Models.FilesModelImplement in '..\models\gemini\Models.FilesModelImplement.pas',
  Models.GenerativeModelImplement in '..\models\gemini\Models.GenerativeModelImplement.pas',
  Models.GenerativeModelStatement in '..\models\gemini\Models.GenerativeModelStatement.pas',
  Models.ModelsModelImplement in '..\models\gemini\Models.ModelsModelImplement.pas',

  Applications.BasedApplicationImplement in '..\apps\based\Applications.BasedApplicationImplement.pas',
  Applications.BasedApplicationStatement in '..\apps\based\Applications.BasedApplicationStatement.pas',

  Applications.GeminiBasedApplicationImplement in '..\apps\gemini\based\Applications.GeminiBasedApplicationImplement.pas',
  Applications.GeminiBasedApplicationStatement in '..\apps\gemini\based\Applications.GeminiBasedApplicationStatement.pas',

  Applications.Gemini in '..\apps\gemini\Applications.Gemini.pas',

  Unit1 in 'Unit1.pas' {Form1};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := TRUE;

  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
