unit Constants.ParameterName;

interface

const
  // PARAMETERNAME_HTTP_METHOD HTTP请求类型 如：GET/POST/PUT/DELETE
  PARAMETERNAME_HTTP_METHOD                 = 'Method';
  // PARAMETERNAME_HTTP_ADDRESS HTTP请求地址
  PARAMETERNAME_HTTP_ADDRESS                = 'Address';
  // PARAMETERNAME_HTTP_REQUEST_PARAMETERS HTTP请求数据/请求参数
  PARAMETERNAME_HTTP_REQUEST_PARAMETERS     = 'RequestParameters';
  // PARAMETERNAME_HTTP_REQUEST_HEADER HTTP请求头
  PARAMETERNAME_HTTP_REQUEST_HEADER         = 'RequestHeader';
  // PARAMETERNAME_HTTP_REQUEST_CONTENT HTTP请求内容
  PARAMETERNAME_HTTP_REQUEST_CONTENT        = 'RequestContent';
  // PARAMETERNAME_HTTP_RESPONSE_CODE HTTP响应码
  PARAMETERNAME_HTTP_RESPONSE_CODE          = 'ResponseCode';
  // PARAMETERNAME_HTTP_RESPONSE_HEADER HTTP响应头
  PARAMETERNAME_HTTP_RESPONSE_HEADER        = 'ResponseHeader';
  // PARAMETERNAME_HTTP_RESPONSE_CONTENT HTTP响应内容
  PARAMETERNAME_HTTP_RESPONSE_CONTENT       = 'ResponseContent';
  // PARAMETERNAME_HTTP_LOCALE_FILE_NAME 本地文件名
  PARAMETERNAME_HTTP_LOCALE_FILE_NAME       = 'LocaleFileName';
  // PARAMETERNAME_HTTP_REMOTE_FILE_NAME 远程文件名
  PARAMETERNAME_HTTP_REMOTE_FILE_NAME       = 'RemoteFileName';
  // PARAMETERNAME_HTTP_FILE_MIME_TYPE 文件的mime类型
  PARAMETERNAME_HTTP_FILE_MIME_TYPE         = 'FileMimeType';

  // PARAMETERNAME_URL_SCHEME 链接中的请求方案，如：HTTP、HTTPS、FTP、FTPS、WS、WSS等
  PARAMETERNAME_URL_SCHEME                  = 'scheme';
  // PARAMETERNAME_URL_USERNAME 连接中的账户
  PARAMETERNAME_URL_USERNAME                = 'username';
  // PARAMETERNAME_URL_PASSWORD 连接中的密码
  PARAMETERNAME_URL_PASSWORD                = 'password';
  // PARAMETERNAME_URL_HOST 链接中的域名或服务器地址
  PARAMETERNAME_URL_HOST                    = 'host';
  // PARAMETERNAME_URL_PORT 链接中的端口
  PARAMETERNAME_URL_PORT                    = 'port';
  // PARAMETERNAME_URL_PATH 链接中的路径、即页面在服务器上的地址（包括页面文件名）
  PARAMETERNAME_URL_PATH                    = 'path';
  // PARAMETERNAME_URL_QUERY 链接中的参数，即问号【?】后面的内容
  PARAMETERNAME_URL_QUERY                   = 'query';
  // PARAMETERNAME_URL_FRAGMENT 链接中的注释，即井号【#】后面的内容
  PARAMETERNAME_URL_FRAGMENT                = 'fragment';

  // PARAMETERNAME_PROXY_ADDRESS 代理服务器地址，如：socks5://127.0.0.1:1080
  PARAMETERNAME_PROXY_ADDRESS               = 'ProxyAddress';
  // PARAMETERNAME_PROXY_SERVER_HOST 代理服务器名/地址，如：127.0.0.1 | ::1
  PARAMETERNAME_PROXY_SERVER_HOST           = 'ProxyServerHost';
  // PARAMETERNAME_PROXY_SERVER_PORT 代理服务器端口
  PARAMETERNAME_PROXY_SERVER_PORT           = 'ProxyServerPort';
  // PARAMETERNAME_PROXY_USERNAME 代理服务器登录账户
  PARAMETERNAME_PROXY_USERNAME              = 'ProxyUsername';
  // PARAMETERNAME_PROXY_PASSWORD 代理服务器登录密码
  PARAMETERNAME_PROXY_PASSWORD              = 'ProxyPassword';

implementation

end.
